import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'], // Subset Latin untuk bahasa umum
  weight: ['400', '700'], // Tambahkan variasi berat sesuai kebutuhan
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={poppins.className}
      >
        <Navbar /> 
        {children}
      </body>
    </html>
  );
}
